<?php
%A%
echo Nette\Bridges\FormsLatte\FormMacros::renderFormBegin($form = $_form = $_control["myForm"], array()) ;echo Nette\Bridges\FormsLatte\FormMacros::renderFormEnd($_form) ?>


<form<?php echo Nette\Bridges\FormsLatte\FormMacros::renderFormBegin($form = $_form = $_control["myForm"], array (
), FALSE) ?>>
<?php echo Nette\Bridges\FormsLatte\FormMacros::renderFormEnd($_form, FALSE) ?></form>
